unique_values = {'A',2,3,4,'B'}
list_with_doubles = ['a','a',1,1,1,1,2,2,3,3,4]
new_set = set(list_with_doubles)
list_with_doubles = list(new_set)
print(list_with_doubles)
print(len(unique_values))
second_unique_values = {2,3,4}
print(2 in unique_values)
print(unique_values.isdisjoint(second_unique_values))
print(second_unique_values.issubset(unique_values))
print(second_unique_values<unique_values)
print(unique_values.issuperset(second_unique_values))
third_unique_values = {4,5,6}
print(third_unique_values.union(second_unique_values))
print(third_unique_values.intersection(second_unique_values))
print(third_unique_values.difference(second_unique_values))
print(third_unique_values.symmetric_difference(second_unique_values))
#second_unique_values.update(third_unique_values)
#print(second_unique_values)
#second_unique_values.intersection_update(third_unique_values)
#print(second_unique_values)
#second_unique_values.difference_update(third_unique_values)
#print(second_unique_values)
second_unique_values.symmetric_difference_update(third_unique_values)
print(second_unique_values)
second_unique_values.add(4)
print(second_unique_values)
second_unique_values.remove(6)
print(second_unique_values)
second_unique_values.discard(5)
print(second_unique_values)
second_unique_values.pop()
print(second_unique_values)
second_unique_values.clear()
print(second_unique_values)
